apiVersion: v1
kind: Service
metadata:
  name: lucky-numberz-front-end
  namespace: lucky-namespace
  labels:
    app: lucky-numberz-front-end-service
spec:
  type: LoadBalancer
  selector:
    app: lucky-numberz-front-end-service
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None

